### ISSUE TITLE
Refine Requirement: Provide feedback to USPS on the links or barcodes visited

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#11]
Requirement needs to be analyzed for the state it is in in the current application (it may appear fully complete), which should then drive questions to the customer about what they truly want. Document findings as a comment here. Questions can be asked to the team or put into the "Customer Questions" document in the General/Files area.

https://github.com/umgc/fall2022/issues/34 will help with this if completed, alternatively you can run the app on your own.

**Comment by AliFahimi** [comment]
Waiting for customer questions on what type of data they want collected. However I'm currently assuming they want data collected on the number of times a link or barcode is visited so we must send something to the back end every time the user selects a link/barcode. Possibly also breaking it up into domains instead of individual barcodes/links depending on the granularity of the data the customer wants
