### ISSUE TITLE
Create mockup of a more usable and aesthetically pleasing login UI

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#239]
The customer has a strong desire for a better overall layout of the application. Mockups are the most effective way to demonstrate our ideas. Please include mockups as an attachment to this issue and the team can provide feedback, after which the SRS can be updated with new mockups.

**Comment by AndrewAsava** [comment]
![Image](https://user-images.githubusercontent.com/93182173/189170564-67990beb-7e42-413a-88e8-77ba7643e30a.png)
![Image](https://user-images.githubusercontent.com/93182173/189170565-ce1f6f37-737c-49ba-99d7-f79f6f19c32e.png)

First draft of Login UI Mockup. 

Could add something like a toggle function to remember user details near the "Forgot Password?" function. Feedback is welcome, especially if I'm going in the completely wrong direction.

**Comment by shaneknows** [comment]
I love it, but the issue is they are entering their email information here and not their USPS account information. This does bring up a big flaw in the current setup though. I feel like ideally we would just tie into the USPS existing api and get this info. Maybe it isn't written in a very accessible way though.

I think the look of this is great, but we should change it to explain that they are entering their email account information that is associated with USPS Informed Delivery and not their USPS account info. The sign up now link is a great additional feature that I think the customer will love.

**Comment by tatikozh** [comment]
Looks great! Agree with Shane that we probably need to change username to email as we currently don't use accounts. Also, in regards to visually impaired users, shall we include a microphone icon at the bottom of the page or think of another way of the login process for users with disabilities?

**Comment by cthorn2** [comment]
Jumping in because I love the direction.  How about something like this?  I was trying to play of the USPS theme with the logo / header, so I went with Closer Inspection, but suggestions welcome.
![email-login-retrieve-screen](https://user-images.githubusercontent.com/111912838/189414852-2a726ce2-60ea-4c6e-b85b-9b2952b211e4.png)

**Comment by cthorn2** [comment]
Also, we might want to start thinking about standardizing the palette colors.  If we're going to use the USPS colors, we should use those that they use on their website.
![UI USPS Palette options](https://user-images.githubusercontent.com/111912838/189415200-9d60f7b9-c310-4ab6-a881-a4e097296134.jpg)

**Comment by mdconatser** [comment]
- good stuff here overall, I agree with Chris on the palette and the updates he added. 
- I think we should still retain something like "Not registered for USPS Informed Delivery messages? Click here to sign up" so a user can more easily add this if they aren't signed up already.
- I don't think we need to add any voice input features here, since that should be provided by the OS and not us.
- Privacy policy link at bottom?
