### ISSUE TITLE
Document App Store release concerns for caching user emails

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#427]
As a developer, I need to know that we are meeting Apple/Google's guidelines for storing user data like emails. This will make the submission process less of a risk of rejection.

Acceptance Criteria
--
- Apple/Google app store guidelines for storing user data (like emails) is thoroughly evaluated for our specific plans
- Findings an especially actions required is left as comments in this Issue

**Comment by wpbear1742** [comment]
Apple Guidelines

https://developer.apple.com/app-store/app-privacy-details/

The App Store better helps users understand an app’s privacy practices before they download the app. On each app’s product page, users can learn about some of the data types an app may collect, and whether the information is used to track them or is linked to their identity or device.

In order to submit new apps and app updates, you must provide information about your privacy practices in App Store Connect. If you use third-party code — such as advertising or analytics SDKs — you need to describe what data the third-party code collects, how the data may be used, and whether the data is used to track users.

Analytics | Using data to evaluate user behavior, including to understand the effectiveness of existing product features, plan new features, or measure audience size or characteristics

You use Apple frameworks or services, such as MapKit, CloudKit, or App Analytics.
If you collect data about your app from Apple frameworks or services, you should indicate what data you collect and how you use it. You are not responsible for disclosing data collected by Apple.

**Comment by wpbear1742** [comment]
Google Guidelines

https://support.google.com/googleplay/android-developer/answer/10787469?hl=en#in_play_console&zippy=%2Cwhat-users-will-see-if-your-app-shares-user-data%2Cdata-collection%2Cdata-types%2Ctimeline-information%2Cwatch-the-data-safety-form-walkthrough-video

link to data safety form - https://play.google.com/console/app/app-content/summary

Provide information for Google Play's Data safety section
In [July](https://android-developers.googleblog.com/2021/07/new-google-play-safety-section.html) and [October](https://android-developers.googleblog.com/2021/10/launching-data-safety-in-play-console.html) 2021, we announced additional details for the Data safety section on Google Play following our initial blog post in [May 2021](https://android-developers.googleblog.com/2021/05/new-safety-section-in-google-play-will.html). Developers are required to tell us about their apps' privacy and security practices by completing a form in Play Console. This information will be shown on your app's store listing to help Google Play users understand how your app collects and shares user data before they download.

This article provides an overview of the new requirements, what you need to do to complete the form, and a timeline of upcoming events.

After July 20, 2022, all apps will be required to have completed an accurate Data safety form that discloses their data collection and sharing practices (including apps that do not collect any user data).

https://youtu.be/4rfF3y4xchU
