### ISSUE TITLE
Document App Store guidelines for potential background task for our notifications process

### ISSUE THREAD

**Issue by mdconatser** [umgc/fall2022#429]
As a developer, I need to know that we are meeting Apple/Google's guidelines for utilizing a background refresh of a user's emails to support OS notifications. This will make the submission process less of a risk of rejection.

Acceptance Criteria
--
- Apple/Google app store guidelines for background refresh that would support our OS notifications integration is thoroughly evaluated for our specific plans
- Findings and especially actions required is left as comments in this Issue

**Comment by umgcjack** [comment]
The current implementation of the background service library provided by Flutter does not allow for the scheduling of reoccurring background tasks yet. As such, this app should not be concerned with Apple's background refresh policies.

The Android implementation does not require additional Google Play considerations, since it is not using any location services when performing the background task.
